


List<Map<String , dynamic>> detail = [
  {
    "Cname": "Google",
    "Clogo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png",
    "coepick": "https://static.toiimg.com/thumb/msid-73204368,width-400,resizemode-4/73204368.jpg",
    "ceoname": "Sundar Pichhai",
    'log' : -122.00892843030311,
    'lat' : 37.33493621091769,
    "dis": "Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock",
  },
  {
    "Cname": "Microsoft",
    "Clogo": "https://agsol.com/wp-content/uploads/2018/09/new-microsoft-logo-SIZED-SQUARE.jpg",
    "coepick": "https://upload.wikimedia.org/wikipedia/commons/7/78/MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg",
    "ceoname": "Satya Nadela",
    'log' : -122.1237,
    'lat' : 47.6371,
    "dis": "Microsoft Corporation is an American multinational technology corporation producing computer software, consumer electronics, personal computers, and related services. ",
  },
  {
    "Cname": "Apple",
    "Clogo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png",
    "coepick": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ50DJ6A-7yyGRWd8V9i5dSIhZI7z93Snp8dvn5sA7HgA&s",
    "ceoname": "Tim Cook",
    'log' : -122.00892843030311,
    'lat' : 37.33493621091769,
    "dis": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, United States. Apple is the largest technology company by revenue (totaling US\$365.8 billion in 2021) and, as of June 2022,",
  },
  {
    "Cname": "Adani",
    "Clogo": "https://s3-symbol-logo.tradingview.com/adani--600.png",
    "coepick": "https://www.adani.com/-/media/Project/Adani/About-Us/BOD2/BOD2/14/Gautam-Adani-23-1-12-187969.jpg?h=440&la=en&w=420&hash=9F2F8710292583C72A2F3A3678255840",
    "ceoname": "Gautam Adani",
    'log' : 72.852103,
    'lat' : 19.060515,
    "dis": "Adani Group is an Indian multinational conglomerate, headquartered in Ahmedabad. It was founded by Gautam Adani, in 1988 as a commodity trading business,",
  },
  {
    "Cname": "Tesla",
    "Clogo": "https://www.carlogos.org/car-logos/tesla-logo-2200x2800.png",
    "coepick": "https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg",
    "ceoname": "Elon Musk",
    'log' : -97.617134,
    'lat' : 30.222296,
    "dis": "Elon Reeve Musk was born on June 28, 1971, in Pretoria, one of South Africa's capital cities. Musk has British and Pennsylvania Dutch ancestry. His mother is Maye Musk (née Haldeman),",
  },
  {
    "Cname": "Adidas",
    "Clogo": "https://thumbs.dreamstime.com/b/adidas-ag-multinational-corporation-founded-headquartered-herzogenaurach-germany-designs-manufactures-shoes-139136442.jpg",
    "coepick": "https://www.adidas-group.com/media/filer_public_thumbnails/filer_public/71/cc/71cc6e9f-0bab-43a0-866a-19e1f5d8cfc8/kasper_rorsted_portrait_laces_neu.jpg__800x900_q85_crop-smart_subject_location-1650%2C833_subsampling-2.jpg",
    "ceoname": "Herbert Hainer",
    'log' : 74.940147,
    'lat' : 30.212601,
    "dis": "Adidas AG (German: [ˈʔadiˌdas] (listen); stylized as adidas since 1949)[4] is a German multinational corporation, founded and headquartered in Herzogenaurach, Bavaria, that designs and manufactures shoes, clothing and accessories.",
  },
  {
    "Cname": "Bharat Pe",
    "Clogo": "https://hindubabynames.info/downloads/wp-content/themes/hbn_download/download/banking-and-finance/bharatpe-logo.png",
    "coepick": "https://images.livemint.com/img/2022/04/05/1600x900/Suhail_Sameer_1649162329574_1649162329843.jpg",
    "ceoname": "Suhail Sameer",
    'log' : 76.680000,
    'lat' : 12.120000,
    "dis": "BharatQR, developed by NPCI, Mastercard, and Visa, is an integrated payment system in India for mobile devices. The system, which was launched in September 2016,",
  },
  {
    "Cname": "Puma",
    "Clogo": "https://static.vecteezy.com/system/resources/previews/010/994/278/original/puma-logo-white-symbol-with-name-clothes-design-icon-abstract-football-illustration-with-black-background-free-vector.jpg",
    "coepick": "https://media.voguebusiness.com/photos/61fd6270fd855c197a6d5e57/2:3/w_2560%2Cc_limit/puma-voguebus-puma-feb-21-story.jpg",
    "ceoname": "Arne Freundt",
    'log' : 34.756125,
    'lat' : -5.003383,
    "dis": "Puma SE, branded as PUMA, is a German multinational corporation that designs and manufactures athletic and casual footwear, apparel and accessories, which is headquartered in Herzogenaurach, Bavaria, Germany.",
  },
];